### ISSUE TITLE
Blank Screen after install

### ISSUE THREAD

**Issue by rovincent** [hydrotik/reaction-hydrotik-plugin#14]
I'm a real noob when it comes to reaction commerce.

I have it working without this plugin, I followed the instructions other than reaction in running on my on severs.

Out put when starting Reaction:
=> Started proxy.
=> Started MongoDB.
12:38:01.822Z  INFO Reaction: Load default data from /private/data/
12:38:02.005Z  INFO Reaction: JobServer started
12:38:02.013Z  WARN Reaction: Skipped loading settings from reaction.json.
12:38:05.676Z  INFO Reaction: Reaction Version: 1.4.1
12:38:05.776Z  WARN Reaction: OpenExchangeRates API not configured. Not adding fetchRates job
12:38:05.781Z  WARN Reaction: OpenExchangeRates API not configured. Not adding flushRates job
12:38:05.971Z  INFO Reaction: ::: Modifying checkout workflow
12:38:05.978Z  INFO Reaction: ::: Adding about route permissions to default roles
12:38:06.034Z  INFO Reaction: ::: changing all layouts to coreLayoutHydrotik
12:38:06.200Z  INFO Reaction: Reaction initialization finished.
=> Started your app.

=> App running at: http://localhost:3000/

But when it loads in a browser in source i see all the javascript loaded but there is nothing that displays anything in the body. The browser is not seeing any errors in the console and server does not report anything.

My thoughts are this is something very basic ive missed.

Because I'm running reaction on my own server i did not follow anything that looked specific to Heroku. Also was a little confused at the comment related to the public folder so i just copied the contents in to the root of the plugin however this was after the first blank page load and copying the files made no difference.

By the way this was loaded on to a brand new #reaction init

**Comment by rovincent** [comment]
OK just realized there is a reaction/public (never used that in all the testing ive done so far).

I copied the contents of public to reaction/public but still blank screen in browser.

**Comment by rovincent** [comment]
So under React dev component in Chrome it seems to be loading the slider but everything is zero hieght ?

at the end of the page source there is a react root section. that contains the following from 2 to 26?

**Comment by rovincent** [comment]
In the console of Firefox i get an error: 

Exception from Tracker recompute function:  meteor.js:934:11
Error: No such template: tagNav

Not much on Google that seems to apply, not sure why i dont get this in Chrome.

**Comment by rovincent** [comment]
Ok after clearing the cash in Chrome i now get the same tagNav error in Chrome.

**Comment by rovincent** [comment]
Well running reaction pull and then reaction update installs 2 extra packages:

├── react-select@1.0.0-rc.6
└── transliteration@1.6.2  (git://github.com/reactioncommerce/transliteration.git#699d48cc8dd9a64f1a2773e1b36b6faa4bbdca2f)

but it complete blows up the plugin, 90 js errors reagarding es5 shim.

Starting again.....

**Comment by rovincent** [comment]
Well for now im throwing in the towel,

It seems to be (to me, with the very little knowledge I have of Reaction) some missing import into the core functionality.

**Comment by brent-hoover** [comment]
@rovincent This plugin was created quite a while ago. Not sure it's been kept up to date with the changes to Reaction.

**Comment by hydrotik** [comment]
Out of date example. Hopefully I get a chance to work with the updated version soon.
